source/apps/menu/urls.py
from macrosurl import url
from django.conf.urls import patterns

from .views import AjaxCommunitiesPanel, AjaxFollowingPanel, AjaxNotificationsPanel, AjaxNotificationsCount


urlpatterns = patterns(
    '',
    url(r'^communities$', AjaxCommunitiesPanel.as_view(), name='communities_ajax'),
    url(r'^following', AjaxFollowingPanel.as_view(), name='following_ajax'),
    url(r'^notifications/count', AjaxNotificationsCount.as_view(), name='notifications_count_ajax'),
    url(r'^notifications', AjaxNotificationsPanel.as_view(), name='notifications_ajax'),
)

source/apps/post/urls.py
from macrosurl import url

from django.conf.urls import patterns, include

from .views import PostDetail, PostDelete, PostCreate


urlpatterns = patterns(
    '',
    url(r'create/$', PostCreate.as_view(), name='create_ajax', kwargs={'model': 'post.Post'}),

    url(r':pk/$', PostDetail.as_view(), name='detail'),
    url(r':pk/delete/$', PostDelete.as_view(), name='delete_ajax'),

    url(r':pk/', include('apps.share.urls', namespace='share'), {'model': 'post.Post'}),

)

source/apps/save/urls.py
from macrosurl import url
from django.conf.urls import patterns

from .views import AjaxSaveCreateView, AjaxSaveRemoveView, SavedListView


urlpatterns = patterns(
    '',
    url(r'^save/$', SavedListView.as_view(), name='list'),

    url(r'^post/:pk/save/$', AjaxSaveCreateView.as_view(), {'model': 'post.Post'}, name='save_ajax'),
    url(r'^post/:pk/unsave/$', AjaxSaveRemoveView.as_view(), {'model': 'post.Post'}, name='unsave_ajax'),
)

source/apps/users/urls.py
from django.conf.urls import patterns, url
from apps.users.views import LoginView, LogoutView, RegisterView, UserDetailsView, UsernameVariationView, \
    PasswordResetView, ProfileDeleteView

urlpatterns = patterns(
    '',
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'register/$', RegisterView.as_view(), name='register_ajax'),
    url(r'user-details/$', UserDetailsView.as_view(), name='user-details'),
    url(r'username-variants/$', UsernameVariationView.as_view(), name='user-variants'),
    url(r'reset-password/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'delete/$', ProfileDeleteView.as_view(), name='delete'),
)

source/apps/wall/urls.py
from macrosurl import url

from django.conf.urls import patterns
from apps.wall.views import WallList, CommunityWallList, AjaxMarkWallPostAsRead, WallOwnPostsList

urlpatterns = patterns(
    '',

    url(r'^user/', WallList.as_view(), name='user'),
    url(r'^user/own/', WallOwnPostsList.as_view(), name='own'),
    url(r'^user/:pk/', WallList.as_view(), name='detail'),

    url(r'^community/:pk/', CommunityWallList.as_view(), name='community'),

    url(r'^post/:pk/is_read', AjaxMarkWallPostAsRead.as_view(), name='is_read')

)

source/lib/users/urls.py
from django.conf.urls import patterns, url
from apps.users.views import LoginView, LogoutView
from lib.users.views import PasswordResetView, PasswordResetConfirmView


urlpatterns = patterns(
    '',
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'reset-password/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

source/urls.py
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from throttle.decorators import throttle


urlpatterns = patterns('')

if settings.INSTANCE_TYPE == 'www' or not settings.CHECK_DOMAIN_SEPERATION:
    from apps.core.views import RedirectToDefaultLanguage, HomeView

    handler404 = 'apps.core.views.handle_404'
    handler500 = 'apps.core.views.handle_500'

    urlpatterns += patterns(
        '',
        url(r'^$', RedirectToDefaultLanguage.as_view(permanent=False), name='redirect_to_default_language'),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

    urlpatterns += i18n_patterns(
        '',
        url(r'^$', HomeView.as_view(), name='home'),
        url(r'^wall/', include('apps.wall.urls', namespace='wall')),
        url(r'^post/', include('apps.post.urls', namespace='post')),

        url(r'', include('apps.block.urls', namespace='block')),
        url(r'', include('apps.comment.urls', namespace='comment')),
        url(r'', include('apps.follow.urls', namespace='follow')),
        url(r'', include('apps.like.urls', namespace='like')),
        url(r'', include('apps.save.urls', namespace='save')),
        url(r'', include('apps.share.urls', namespace='share')),
        url(r'', include('apps.suggestions.urls', namespace='suggestions')),
        url(r'', include('apps.community.urls', namespace='community')),
        url(r'', include('apps.notifications.urls', namespace='notifications')),
        url(r'', include('apps.report.urls', namespace='report')),

        url(r'^account/', include('apps.users.urls', namespace='users')),
        url(r'^search/', include('apps.search.urls', namespace='search')),
        url(r'^menu/', include('apps.menu.urls', namespace='menu')),

        # NOTE!! this should be last, as it matches every "single" url path part (r'^(?P<slug>[-\w]+)/$')
        url(r'', include('apps.cms.pages.urls', namespace='pages')),

    )

if settings.INSTANCE_TYPE == 'admin' or not settings.CHECK_DOMAIN_SEPERATION:
    admin.autodiscover()
    
    login_func = admin.site.login
    
    # Fugly workaround for django-throttle-request:
    # admin.site.login = throttle(admin.site.login) doesn't work, because
    # throttle adds an attribute to the passed view_func, which in this case
    # is an instancemethod of admin.site. This results in an error
    @throttle(zone='admin-login')
    def throttled_login(*args, **kwargs):
        return login_func(*args, **kwargs)
    
    admin.site.login = throttled_login
    admin.site.site_header = 'JoopeA'
    admin.site.site_title = 'JoopeA'
    admin.site.index_title = 'Site administration'

    urlpatterns += patterns(
        '',
        url(r'^admin/report/', include('apps.report.admin_urls', namespace="admin_reports")),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

if settings.INSTANCE_TYPE == 'shorturl':
    urlpatterns = patterns(
        '',
        url(r'', include('apps.shorturl.urls', namespace='shorturl'), name='redirect_to_default_language'),
    )

if settings.INSTANCE_TYPE in ('www', 'admin') and settings.DEBUG:
    from apps.core.views import DebugView

    urlpatterns += patterns(
        '',
        url(
            r"^media/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.MEDIA_ROOT,
             "show_indexes": True}
        ),
        url(
            r"^static/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.STATIC_ROOT,
             "show_indexes": True}
        ),
        url(
            r'^csrf_token', DebugView.as_view()
        )
    )
    urlpatterns += staticfiles_urlpatterns()


handler404 = 'apps.core.views.handle_404'
handler500 = 'apps.core.views.handle_500'

source/apps/menu/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, View
from django.http import HttpResponseForbidden, JsonResponse
from apps.users.forms import LoginForm
from apps.users.queries import UserProfile

from apps.community.queries import MenuUserCommunityDataView
from apps.follow.queries import MenuUserFollowUserDataView
from apps.notifications.queries import NotificationDataView


class WithUserMenu(object):
    def get_context_data(self, *args, **kwargs):
        context = super(WithUserMenu, self).get_context_data(*args, **kwargs)
        context['profile'] = UserProfile.get(self.request.user.pk)
        if not self.request.user.is_authenticated():
            context['login_form'] = LoginForm(prefix='user')
            context['login_form_action'] = reverse_lazy("users:login")
        return context


class AjaxCommunitiesPanel(TemplateView):
    template_name = 'menu/ajax/_communities.html'

    def get_context_data(self, **kwargs):
        context = super(AjaxCommunitiesPanel, self).get_context_data(**kwargs)
        context['communities'] = list(MenuUserCommunityDataView.list(user_id=self.request.user.id))
        return context

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
            return HttpResponseForbidden()
        return super(AjaxCommunitiesPanel, self).get(self, *args, **kwargs)


class AjaxFollowingPanel(TemplateView):
    template_name = 'menu/ajax/_following.html'

    def get_context_data(self, **kwargs):
        context = super(AjaxFollowingPanel, self).get_context_data(**kwargs)
        context['following'] = list(MenuUserFollowUserDataView.list(user_id=self.request.user.id))
        return context

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
            return HttpResponseForbidden()
        return super(AjaxFollowingPanel, self).get(self, *args, **kwargs)


class AjaxNotificationsPanel(TemplateView):
    template_name = 'menu/ajax/_notifications.html'

    def get_context_data(self, **kwargs):
        context = super(AjaxNotificationsPanel, self).get_context_data(**kwargs)
        context['notifications'] = NotificationDataView.by_user(user_id=self.request.user.id)
        return context

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated():
            return HttpResponseForbidden()
        return super(AjaxNotificationsPanel, self).get(self, *args, **kwargs)


class AjaxNotificationsCount(View):
    http_method_names = ['get']

    def get(self, *args, **kwargs):
        return JsonResponse(
            NotificationDataView.get_unread_notifications_count(user_id=self.request.user.id),
            safe=False
        )

source/apps/users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView, View
from formtools.wizard.views import SessionWizardView

from apps.core.views import AjaxFormResponseMixin
from apps.users.queries import UserDataView, UsernameVariationDataView, UserDataView
from apps.users.forms import LoginForm, UserRegistrationForm, UserChangeForm, PWResetFormQuestion, PWResetUsernameForm, \
    SetPasswordForm, PasswordConfirmationForm
from lib.users.mixins import LanguageRedirectMixin
from lib.users.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from apps.block.views import BlockedUsers
from apps.follow.views import FollowingUserUsers, FollowedUserUsers
from apps.menu.views import WithUserMenu


class LoginView(LanguageRedirectMixin, BaseLoginView):
    template_name = 'users/login.html'
    form_class = LoginForm
    form_action = reverse_lazy("users:login")
    prefix = 'user'

    def form_valid(self, form):
        self.language = form.get_user().language

        result = super(LoginView, self).form_valid(form)
        return result

    def form_invalid(self, form):
        return super(LoginView, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context.update(
            {
                'form_action': str(self.form_action),
                'login_form': context.pop('form', None)
            }
        )
        return context


class LogoutView(BaseLogoutView):
    pass


class RegisterView(AjaxFormResponseMixin, FormView):
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    form_css_class = 'register-form'
    submit_name = 'Register'
    form_action = reverse_lazy("users:register_ajax")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(self.get_next_url())
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super(RegisterView, self).get_initial()
        # initial['username'] = self.request.GET.get('username', '')
        return initial

    def form_valid(self, form):

        form.save()
        form.authenticate_and_login(self.request)
        # messages.success(self.request, _('Thank you! Your registration was successfull. You are now logged in.'))

        context = {}
        return JsonResponse(
            {
                'success': True,
                'data': self.get_context_data(**context)
            }
        )

    def get_success_url(self):
        return self.get_next_url()

    def get_next_url(self):
        return self.request.GET.get('next', '/')

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)

        context.update({
            "form_css_class": self.form_css_class,
            "submit_name": self.submit_name,
            "form_action": str(self.form_action)
        })

        return context


class UserDetailsView(WithUserMenu, FollowedUserUsers, FollowingUserUsers, BlockedUsers, LanguageRedirectMixin, FormView):
    template_name = 'users/user_details.html'
    form_css_class = 'user-detail-form'
    form_class = UserChangeForm
    submit_name = _('Save')
    object = None
    default_redirect_param = reverse_lazy("users:user-details")
    allow_logged_in = True

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = super(UserDetailsView, self).get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object})
        return kwargs

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):

        self.object = self.get_object()

        return super(UserDetailsView, self).dispatch(request, *args, **kwargs)

    def get_object(self):
        self.object = UserDataView.by_id(self.request.user.id)
        return self.object

    def form_valid(self, form):

        form.save()
        self.language = form.get_language()
        messages.success(self.request, _('Your profile is updated.'))

        return super(UserDetailsView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(UserDetailsView, self).get_context_data(**kwargs)

        context.update({
            "form_css_class": self.form_css_class,
            "submit_name": self.submit_name,
        })

        return context


class UsernameVariationView(View):

    def get(self, request, *args, **kwargs):
        variations = UsernameVariationDataView.by_username(request.GET.get('username_id'))
        data = serializers.serialize('json', variations, fields=('id', 'username_variation_no'))
        return HttpResponse(data, content_type='application/json')


PW_FORMS = [("username", PWResetUsernameForm),
         ("sec-question1", PWResetFormQuestion),
         ("sec-question2", PWResetFormQuestion),
         ("confirmation", SetPasswordForm)]


class PasswordResetView(SessionWizardView):
    template_name = 'users/pw_reset.html'
    form_list = PW_FORMS
    user = None

    def done(self, form_list, **kwargs):
        for form in form_list:
            if hasattr(form, 'save'):
                form.save()

        return HttpResponseRedirect('/')

    def get_form(self, step=None, data=None, files=None):
        form = super(PasswordResetView, self).get_form(step, data, files)

        if not step:
            step = self.steps.current

        if step == 'sec-question1':
            form.user = self.get_user()
            form.answer = form.user.security_answer_1
            form.question = form.user.security_question_1

        if step == 'sec-question2':
            form.user = self.get_user()
            form.answer = form.user.security_answer_1
            form.question = form.user.security_question_2

        if step == 'confirmation':
            form.user = self.get_user()
            form.question = _("Please specify your new password. You will be directed to the homepage after successfully setting the new password.")

        return form

    def get_user(self):
        username = self.get_cleaned_data_for_step('username').get('username')
        return UserDataView.by_username(username)


class ProfileDeleteView(WithUserMenu, FormView):
    template_name = 'users/delete.html'
    form_class = PasswordConfirmationForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ProfileDeleteView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'user': self.request.user
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form):
        form.save(self.request)
        return HttpResponseRedirect('/')

source/apps/menu/templates/menu/_hamburger.html
<a class="hamburger-menu mm-slideout" href="#menu">
    <i class="fa fa-bars"></i>
</a>

source/apps/menu/templates/menu/_user.html
{% load i18n utils cms_tags %}

{% if user.is_authenticated %}
    <nav id="menu" class="">
        <ul>
            <li class="menu-list-item">
                <span class="menu-link selected">
                    <i class="icon-menu-item fa fa-circle" style="color: {{ profile.user.profile_colour }};"></i> {% trans "My wall" %} ({{ request.user.username }})
                </span>
                <ul>
                    <li class="menu-list-item">
                        <a class="menu-link" href="{% url 'wall:user' %}" style="color: {{ profile.user.profile_colour }};">
                            <i class="icon-menu-item fa fa-circle" style="color: {{ profile.user.profile_colour }};"></i> {% trans "My wall" %}
                        </a>
                    </li>
                    <li class="menu-list-item">
                        <a class="menu-link" href="{% url 'wall:own' %}">
                            <i class="icon-menu-item fa fa-user"></i> {% trans "Own posts" %}
                        </a>
                    </li>
                    <li class="menu-list-item">
                        <a class="menu-link" href="/{{ LANGUAGE_CODE }}/">
                            <i class="fa fa-home"></i> {% trans "Return to homepage" %}
                        </a>
                    </li>
                    <li class="menu-list-item">
                        <a class="menu-link" href="{% url "users:user-details" %}">
                            <i class="fa fa-cogs"></i> {% trans "My settings" %}
                        </a>
                    </li>
                    <li class="menu-list-item">
                        <a data-logout class="menu-link" href="#">
                            <i class="fa fa-sign-out"></i> {% trans "Log Out" %}
                        </a>
                    </li>
                </ul>
            </li>

            <li class="menu-list-item">
                <a class="menu-link" data-create-post href="#">
                    <i class="icon-menu-item fa fa-pencil-square-o"></i> {% trans "New Post" %}
                </a>
            </li>

            <li class="menu-list-item notifications-menu-item">
                <span class="menu-link{% if profile.new_notifications %} notification-alert{% endif %}">
                    <i class="icon-menu-item fa fa-bell">
                        <span class="new-notification"></span>
                    </i>
                    {% trans "Notifications" %}
                </span>
                <ul>
                    {% for notification in profile.notifications.items %}
                        {% include "notifications/_notification_list_item.html" %}
                    {% endfor %}

                    {% if profile.notifications.items %}
                        <li>
                            <a class="menu-detail-link" href="{% url 'notifications:list' %}">{% trans "All notifications" %}</a>
                        </li>

                    {% else %}
                        <li>
                            <p class="empty-state">{% trans "There are no new notifications" %}</p>
                        </li>
                    {% endif %}
                </ul>
            </li>
            <li class="menu-list-item"><a class="menu-link" href="{% url 'save:list' %}"><i
                    class="icon-menu-item fa fa-star"></i> {% trans "Saved Posts" %}</a></li>
            <li class="menu-list-item"><a class="menu-link" href="{% url 'suggestions:list' %}"><i
                    class="icon-menu-item fa fa-thumb-tack"></i> {% trans "Suggestions" %}</a></li>
            <li class="Spacer"></li>
            <li class="menu-list-item community-menu-item">
            <span class="menu-link">
                <i class="icon-paperclip"></i>
                <i class="icon-menu-item fa fa-users"></i>
                {% trans "Communities following" %}
            </span>
                <ul>
                    {% for community in profile.communities %}
                        {% include 'community/_community_small.html' %}
                    {% endfor %}

                    {% if not profile.communities %}
                        <li>
                            <p class="empty-state">{% trans "You are not following any communties" %}</p>
                        </li>
                    {% endif %}
                   <li>
                        <a class="menu-detail-link" href="{% url 'community:list' %}">{% trans "Show all communities" %}</a>
                    </li>
                </ul>
            </li>
            <li class="menu-list-item following-menu-item">
            <span class="menu-link">
                <i class="icon-menu-item fa fa-user"></i>
                {% trans "People following" %}
            </span>
                <ul>
                    {% for followee in profile.following %}
                        <li class="menu-list-item">
                            <a class="menu-link" href="{% url 'wall:detail' pk=followee.target.id %}">
                                <i class="fa fa-circle" style="color: {{ followee.target.profile_colour }}"></i> {{ followee.target.username }}
                            </a>
                        </li>
                    {% endfor %}

                    {% if profile.following %}
                        <li>
                            <a class="menu-detail-link" href="{% url 'users:user-details' %}#tab3">{% trans "All followers" %}</a>
                        </li>

                    {% else %}
                        <li>
                            <p class="empty-state">{% trans "You are not following any people!" %}"</p>
                        </li>
                    {% endif %}
                </ul>
            </li>
            <li class="Spacer"></li>
            <li class="menu-list-item">
                <span class="menu-link selected">
                    <i class="icon-menu-item fa fa-info-circle"></i> {% trans "More information" %}
                </span>
                {% render_page_nav %}
            </li>
            {% if request.user.is_authenticated %}
                <li class="menu-list-item">
                    <a data-logout class="menu-link" href="#">
                        <i class="fa fa-sign-out"></i> {% trans "Log Out" %}
                    </a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% else %}
    <nav id="menu" class="">
        <div class="sidebar-home">
            <h4 class="sidebar-title">{% trans "Why JoopeA Club" %}</h4>

            <p>{% trans "Why choose JoopeA Long Desc" %}
            </p>
            <ul>
              <li class="menu-list-item">
                  <span class="menu-link">
                      <i class="icon-menu-item fa fa-info-circle"></i>
                      {% trans "More information" %}
                  </span>
                  {% render_page_nav %}
              </li>
            </ul>

            {% if login_form %}
            <div class="login-form">
                <h4>{% trans "Login / Signup" %}</h4>
                {% with login_form as form %}
                    <form method="{{ method|default:"post" }}" class="{{ form_css_class|default:"default-form" }}"
                          action="{{ login_form_action|default:"" }}">
                        {% if form.non_field_errors %}{{ form.non_field_errors }}{% endif %}
                        {% csrf_token %}
                        {{ form|render_form }}
                        <a href="#" data-register class="btn sign-up">{% trans "Sign Up" %}</a>
                        <input class="btn-submit" type="submit" value="{% trans "Login" %}"/>
                    </form>
                {% endwith %}
            </div>
            {% endif %}


            <ul>
                <li class="menu-list-item" style="text-align:left;">
                  <a href="{% url 'community:list' %}">
                    <span class="menu-link"><i class="icon-menu-item fa fa-users"></i>
                     {% trans "List of all communities" %}
                    </span>
                   </a>
                 </li>
            </ul>

        </div>
    </nav>
{% endif %}