source/apps/post/urls.py
from macrosurl import url

from django.conf.urls import patterns, include

from .views import PostDetail, PostDelete, PostCreate


urlpatterns = patterns(
    '',
    url(r'create/$', PostCreate.as_view(), name='create_ajax', kwargs={'model': 'post.Post'}),

    url(r':pk/$', PostDetail.as_view(), name='detail'),
    url(r':pk/delete/$', PostDelete.as_view(), name='delete_ajax'),

    url(r':pk/', include('apps.share.urls', namespace='share'), {'model': 'post.Post'}),

)

source/lib/users/urls.py
from django.conf.urls import patterns, url
from apps.users.views import LoginView, LogoutView
from lib.users.views import PasswordResetView, PasswordResetConfirmView


urlpatterns = patterns(
    '',
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'reset-password/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

source/urls.py
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from throttle.decorators import throttle


urlpatterns = patterns('')

if settings.INSTANCE_TYPE == 'www' or not settings.CHECK_DOMAIN_SEPERATION:
    from apps.core.views import RedirectToDefaultLanguage, HomeView

    handler404 = 'apps.core.views.handle_404'
    handler500 = 'apps.core.views.handle_500'

    urlpatterns += patterns(
        '',
        url(r'^$', RedirectToDefaultLanguage.as_view(permanent=False), name='redirect_to_default_language'),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

    urlpatterns += i18n_patterns(
        '',
        url(r'^$', HomeView.as_view(), name='home'),
        url(r'^wall/', include('apps.wall.urls', namespace='wall')),
        url(r'^post/', include('apps.post.urls', namespace='post')),

        url(r'', include('apps.block.urls', namespace='block')),
        url(r'', include('apps.comment.urls', namespace='comment')),
        url(r'', include('apps.follow.urls', namespace='follow')),
        url(r'', include('apps.like.urls', namespace='like')),
        url(r'', include('apps.save.urls', namespace='save')),
        url(r'', include('apps.share.urls', namespace='share')),
        url(r'', include('apps.suggestions.urls', namespace='suggestions')),
        url(r'', include('apps.community.urls', namespace='community')),
        url(r'', include('apps.notifications.urls', namespace='notifications')),
        url(r'', include('apps.report.urls', namespace='report')),

        url(r'^account/', include('apps.users.urls', namespace='users')),
        url(r'^search/', include('apps.search.urls', namespace='search')),
        url(r'^menu/', include('apps.menu.urls', namespace='menu')),

        # NOTE!! this should be last, as it matches every "single" url path part (r'^(?P<slug>[-\w]+)/$')
        url(r'', include('apps.cms.pages.urls', namespace='pages')),

    )

if settings.INSTANCE_TYPE == 'admin' or not settings.CHECK_DOMAIN_SEPERATION:
    admin.autodiscover()
    
    login_func = admin.site.login
    
    # Fugly workaround for django-throttle-request:
    # admin.site.login = throttle(admin.site.login) doesn't work, because
    # throttle adds an attribute to the passed view_func, which in this case
    # is an instancemethod of admin.site. This results in an error
    @throttle(zone='admin-login')
    def throttled_login(*args, **kwargs):
        return login_func(*args, **kwargs)
    
    admin.site.login = throttled_login
    admin.site.site_header = 'JoopeA'
    admin.site.site_title = 'JoopeA'
    admin.site.index_title = 'Site administration'

    urlpatterns += patterns(
        '',
        url(r'^admin/report/', include('apps.report.admin_urls', namespace="admin_reports")),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

if settings.INSTANCE_TYPE == 'shorturl':
    urlpatterns = patterns(
        '',
        url(r'', include('apps.shorturl.urls', namespace='shorturl'), name='redirect_to_default_language'),
    )

if settings.INSTANCE_TYPE in ('www', 'admin') and settings.DEBUG:
    from apps.core.views import DebugView

    urlpatterns += patterns(
        '',
        url(
            r"^media/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.MEDIA_ROOT,
             "show_indexes": True}
        ),
        url(
            r"^static/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.STATIC_ROOT,
             "show_indexes": True}
        ),
        url(
            r'^csrf_token', DebugView.as_view()
        )
    )
    urlpatterns += staticfiles_urlpatterns()


handler404 = 'apps.core.views.handle_404'
handler500 = 'apps.core.views.handle_500'

source/apps/post/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from apps.like.models import LikeAble
from lib.behaviours.models.withurl import WithAbsoluteUrl

from lib.utils.managers import PublishedManager

from lib.behaviours.models.withimage import WithImage
from lib.behaviours.models.withupdates import WithUpdates
from lib.behaviours.models.publishable import PublishAble
from lib.behaviours.models.withuser import WithArchivableAuthor
from lib.behaviours.models.commentable import CommentAble
from lib.behaviours.models.saveable import SaveAble
from lib.behaviours.models.shareable import ShareAble
from lib.behaviours.models.withrichtextcontent import WithRichTextContent
from lib.behaviours.models.withcommunity import WithOptionalCommunity


class Post(WithUpdates, WithRichTextContent, PublishAble, WithArchivableAuthor, LikeAble, CommentAble, SaveAble,
           ShareAble, WithAbsoluteUrl, WithImage, WithOptionalCommunity, models.Model):

    title = models.CharField(_('Title'), max_length=160, db_index=True)
    meta = models.CharField(_('Meta'), max_length=72, null=True)

    active = PublishedManager()
    report_builder_model_manager = active
    all_objects = models.Manager()

    needs_approval = False
    dis_approval_reasons = ''

    language = models.ForeignKey('language.Language', default=settings.LANGUAGE_CODE, to_field='name')

    def __unicode__(self):
        return 'Community: %s - %s' % (unicode(self.community), unicode(self.title[:20]))

    class Meta:
        ordering = ('publish_date', )
        verbose_name = _('Post')
        verbose_name_plural = _("Posts")

source/apps/post/views.py
from django.http import Http404
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django import forms
from django.forms import widgets
from django.forms.utils import flatatt
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from lib.behaviours.views import WithAuthor
from lib.data_views.exceptions import RecordDoesNotExist

from apps.comment.queries import AddPostComments
from apps.core.views import ModelFormView
from apps.core.views import AjaxFormResponseMixin
from apps.menu.views import WithUserMenu
from apps.post.queries import PostShareCount
from apps.wall.queries import WallPostDataView

from .models import Post
from .forms import PostForm


class PostDetail(WithUserMenu, DetailView):
    template_name = 'post/post_detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['is_expanded'] = True

        AddPostComments.all(post=self.object)

        return context


class PostCreate(WithAuthor, ModelFormView, AjaxFormResponseMixin, CreateView):
    template_name = 'post/popup/_new.html'
    form_class = PostForm

    http_method_names = ['get', 'post']

    def get_context_data(self):
        if hasattr(self, 'object'):
            if self.object.needs_approval:
                return {'approval': _('This post is sent for approval because: {0}').format(unicode(self.object.dis_approval_reasons))}
        return {}


"""
    GET op AjaxModelFormDeleteView geeft ajax response met {"form": <html form>}
        is een ModelForm

    POST op AjaxModelFormDeleteView validate form met ge-submitte data
        als data invalid:
            http 400, {"form": <html form met errors>}
        anders
            http 200, {"success": true, "data": {"message": "<text|object>"}

"""


class ButtonChoicesWidget(widgets.Input):
    input_type = 'submit'

    def __init__(self, attrs=None, choices=()):
        if attrs is not None:
            self.input_type = attrs.pop('type', self.input_type)
        super(ButtonChoicesWidget, self).__init__(attrs)
        self.choices = choices

    def render(self, name, value, attrs=None):
        out = format_html('<span{}>', flatatt(self.build_attrs(attrs)))
        for choice in self.choices:
            out += super(ButtonChoicesWidget, self).render(choice[0], choice[1],
                                                           self.build_attrs(attrs, type=self.input_type, name=name))
        return mark_safe(out + '</span>')


class ButtonChoicesField(forms.ChoiceField):
    widget = ButtonChoicesWidget


class AjaxModelFormDeleteView(AjaxFormResponseMixin, UpdateView):
    def __init__(self, *args, **kwargs):
        self.model = self.form_class._meta.model
        super(AjaxModelFormDeleteView, self).__init__(*args, **kwargs)


class PostDeleteForm(forms.ModelForm):
    YES = 'Yes, delete post'
    NO = 'No'

    CHOICES = (
        (YES, YES),
        (NO, NO)
    )

    yes_no = ButtonChoicesField(choices=CHOICES, label=_('Are you sure you want to delete this post?'), required=True)

    def save(self, commit=True):
        if self.cleaned_data['yes_no'] == self.YES:
            # if this post in on this user's wall and the user is not the owner of this post
            # remove the post from this user's wall
            try:
                wall_post = WallPostDataView.get(user_id=self.data.get('author', 0), post_id=self.instance.pk)
                wall_post.delete()

                PostShareCount.update(self.instance)
            except RecordDoesNotExist:
                raise Http404

            # if the post is owned by this user, delete the post (and let it cascade)
            if self.data.get('author', 0) == self.instance.author.pk:
                self.instance.delete()

        return self.instance

    class Meta:
        model = Post
        fields = (
            'id',
        )


class PostDelete(WithAuthor, AjaxModelFormDeleteView):
    template_name = 'post/popup/_delete.html'
    form_class = PostDeleteForm

    def __init__(self, *args, **kwargs):
        self.is_deleted = False
        super(PostDelete, self).__init__(*args, **kwargs)

    def form_valid(self, form):
        self.is_deleted = bool(str(form.data['yes_no']) == str(form.YES))
        return super(PostDelete, self).form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs = super(PostDelete, self).get_context_data(**kwargs)
        kwargs['valid'] = self.is_deleted
        return kwargs

source/apps/post/templates/post/popup/_delete.html
{% load i18n %}{% if form %}
    <form class="delete-popup" action="{%  url 'post:delete_ajax' pk=view.kwargs.pk %}" method="post">
        {% csrf_token %}

        <h3>{% trans "Delete post" %}</h3>
        {{ form.as_p }}
    </form>
{% endif %}

source/apps/post/templates/post/popup/_new.html
{% load i18n %}{% if form %}
    <form class="form-container" action="{%  url 'post:create_ajax' %}" method="post">
        <div class="new-post-popup" id="new-post-popup">
            <h1 class="title">{% trans "Create a post" %}</h1>
            <h3 class="form-subtitle">{% trans "Socially connect with the other people" %}</h3>
            <div class="post-to-location">
                <div class="form-field">
                    <label for="wall-selector-field" class="form-label">{% trans "Where do you want to post?" %}"</label>
                    <select id="wall-selector-field" name="wall-selector" class="wall-selector">
                        <option value="own">{% trans "My own wall" %}</option>
                        <option value="community">{% trans "Community wall" %}</option>
                        <option value="other">{% trans "Other users wall" %}</option>
                    </select>
                </div>
                <div class="community-option form-field">
                    <label class="form-label">{% trans "Select community" %}</label>
                    {{ form.community }}
                </div>
                <div class="wall-option form-field">
                    <div>
                        <label for="wall-field" class="form-label post-on-wall-name">{% trans "Type in the name of the member" %}</label>
                        <input id="wall-field" type="text" name="wall">
                    </div>
                </div>
            </div>

            <br>

            <div class="form-field post-title-field">
                <label class="form-label">{% trans "Post title" %}</label>
                <span class="tooltip">{% trans "The title can contain 160 characters" %}</span>
                {{ form.title }}
            </div>

            <br>

            <div class="form-field post-content">
                <label class="form-label">{% trans "Post message" %}</label>
                {{ form.message }}
            </div>
            <span class="tooltip">{% trans "To @mention another member you have to add @ infront of their ID. E.g. if you want to mention Aban-11 you have to write '@Aban-11'."%}</span>

            <br>

            {% csrf_token %}
            <div class="form-field image-upload">
                <label class="form-label">{% trans "Image" %}</label>
                <span class="tooltip">{% trans "If you want to add an image to your post you can enter a URL or select one from your pc." %}"</span>
                <input type="hidden" name="image" />
                <div id="image_container" class="mutually-exclusive-widget" style="display:inline-block">
                    <div class="file-select">
                        <input checked="" name="image_radio" id="image_radio_file_popup" type="radio"> <label for="image_radio_file_popup" class="image-label">{% trans "Select image from PC" %}</label>
                        <input id="id_image_0" name="image_0" type="file">
                    </div>
                    <div class="file-upload-url">
                        <input name="image_radio" id="image_radio_url_popup" type="radio"> <label for="image_radio_url_popup" class="image-label">{% trans "Upload image from URL" %}</label>
                        <input id="id_image_1" name="image_1" type="url" placeholder="Image URL">
                    </div>
                </div>
            </div>
            <input class="btn comment-submit post-popup-form-submit-button" type="submit" value='{% trans "Post" %}' required="">
        </div>
        <script>
            var $communityOption = $('.community-option').hide();
            var $wallOption = $('.wall-option').hide();
            $('.wall-selector').change(function (ev) {
                var val = $(ev.target).find(':selected').val();
                $communityOption.hide();
                $wallOption.hide();

                if (val === 'community') {
                    $communityOption.show();
                } else if (val === 'other') {
                    $wallOption.show();
                }
            });

        </script>
    </form>
{% endif %}