source/apps/comment/urls.py
from macrosurl import url

from django.conf.urls import patterns, include

from .views import CommentCreate, CommentList, CommentDelete, FirstAndLastComments


urlpatterns = patterns(
    '',

    url(r'^post/:pk/comment/create/$', CommentCreate.as_view(), name='create'),
    url(r'^post/:pk/comments/more/$', CommentList.as_view(), name='more'),
    url(r'^post/:pk/comments/first_last/$', FirstAndLastComments.as_view(), name='first_and_last'),

    url(r':pk/delete/$', CommentDelete.as_view(), name='delete_ajax'),
    url(r':pk/', include('apps.report.urls', namespace='report'), {'model': 'comment.Comment'}),

)

source/apps/post/urls.py
from macrosurl import url

from django.conf.urls import patterns, include

from .views import PostDetail, PostDelete, PostCreate


urlpatterns = patterns(
    '',
    url(r'create/$', PostCreate.as_view(), name='create_ajax', kwargs={'model': 'post.Post'}),

    url(r':pk/$', PostDetail.as_view(), name='detail'),
    url(r':pk/delete/$', PostDelete.as_view(), name='delete_ajax'),

    url(r':pk/', include('apps.share.urls', namespace='share'), {'model': 'post.Post'}),

)

source/apps/wall/urls.py
from macrosurl import url

from django.conf.urls import patterns
from apps.wall.views import WallList, CommunityWallList, AjaxMarkWallPostAsRead, WallOwnPostsList

urlpatterns = patterns(
    '',

    url(r'^user/', WallList.as_view(), name='user'),
    url(r'^user/own/', WallOwnPostsList.as_view(), name='own'),
    url(r'^user/:pk/', WallList.as_view(), name='detail'),

    url(r'^community/:pk/', CommunityWallList.as_view(), name='community'),

    url(r'^post/:pk/is_read', AjaxMarkWallPostAsRead.as_view(), name='is_read')

)

source/lib/users/urls.py
from django.conf.urls import patterns, url
from apps.users.views import LoginView, LogoutView
from lib.users.views import PasswordResetView, PasswordResetConfirmView


urlpatterns = patterns(
    '',
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'reset-password/$', PasswordResetView.as_view(), name='password-reset'),
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
)

source/urls.py
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from throttle.decorators import throttle


urlpatterns = patterns('')

if settings.INSTANCE_TYPE == 'www' or not settings.CHECK_DOMAIN_SEPERATION:
    from apps.core.views import RedirectToDefaultLanguage, HomeView

    handler404 = 'apps.core.views.handle_404'
    handler500 = 'apps.core.views.handle_500'

    urlpatterns += patterns(
        '',
        url(r'^$', RedirectToDefaultLanguage.as_view(permanent=False), name='redirect_to_default_language'),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

    urlpatterns += i18n_patterns(
        '',
        url(r'^$', HomeView.as_view(), name='home'),
        url(r'^wall/', include('apps.wall.urls', namespace='wall')),
        url(r'^post/', include('apps.post.urls', namespace='post')),

        url(r'', include('apps.block.urls', namespace='block')),
        url(r'', include('apps.comment.urls', namespace='comment')),
        url(r'', include('apps.follow.urls', namespace='follow')),
        url(r'', include('apps.like.urls', namespace='like')),
        url(r'', include('apps.save.urls', namespace='save')),
        url(r'', include('apps.share.urls', namespace='share')),
        url(r'', include('apps.suggestions.urls', namespace='suggestions')),
        url(r'', include('apps.community.urls', namespace='community')),
        url(r'', include('apps.notifications.urls', namespace='notifications')),
        url(r'', include('apps.report.urls', namespace='report')),

        url(r'^account/', include('apps.users.urls', namespace='users')),
        url(r'^search/', include('apps.search.urls', namespace='search')),
        url(r'^menu/', include('apps.menu.urls', namespace='menu')),

        # NOTE!! this should be last, as it matches every "single" url path part (r'^(?P<slug>[-\w]+)/$')
        url(r'', include('apps.cms.pages.urls', namespace='pages')),

    )

if settings.INSTANCE_TYPE == 'admin' or not settings.CHECK_DOMAIN_SEPERATION:
    admin.autodiscover()
    
    login_func = admin.site.login
    
    # Fugly workaround for django-throttle-request:
    # admin.site.login = throttle(admin.site.login) doesn't work, because
    # throttle adds an attribute to the passed view_func, which in this case
    # is an instancemethod of admin.site. This results in an error
    @throttle(zone='admin-login')
    def throttled_login(*args, **kwargs):
        return login_func(*args, **kwargs)
    
    admin.site.login = throttled_login
    admin.site.site_header = 'JoopeA'
    admin.site.site_title = 'JoopeA'
    admin.site.index_title = 'Site administration'

    urlpatterns += patterns(
        '',
        url(r'^admin/report/', include('apps.report.admin_urls', namespace="admin_reports")),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^ckeditor/', include('ckeditor.urls')),
    )

if settings.INSTANCE_TYPE == 'shorturl':
    urlpatterns = patterns(
        '',
        url(r'', include('apps.shorturl.urls', namespace='shorturl'), name='redirect_to_default_language'),
    )

if settings.INSTANCE_TYPE in ('www', 'admin') and settings.DEBUG:
    from apps.core.views import DebugView

    urlpatterns += patterns(
        '',
        url(
            r"^media/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.MEDIA_ROOT,
             "show_indexes": True}
        ),
        url(
            r"^static/(?P<path>.*)$", "django.views.static.serve",
            {"document_root": settings.STATIC_ROOT,
             "show_indexes": True}
        ),
        url(
            r'^csrf_token', DebugView.as_view()
        )
    )
    urlpatterns += staticfiles_urlpatterns()


handler404 = 'apps.core.views.handle_404'
handler500 = 'apps.core.views.handle_500'

source/apps/post/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from apps.like.models import LikeAble
from lib.behaviours.models.withurl import WithAbsoluteUrl

from lib.utils.managers import PublishedManager

from lib.behaviours.models.withimage import WithImage
from lib.behaviours.models.withupdates import WithUpdates
from lib.behaviours.models.publishable import PublishAble
from lib.behaviours.models.withuser import WithArchivableAuthor
from lib.behaviours.models.commentable import CommentAble
from lib.behaviours.models.saveable import SaveAble
from lib.behaviours.models.shareable import ShareAble
from lib.behaviours.models.withrichtextcontent import WithRichTextContent
from lib.behaviours.models.withcommunity import WithOptionalCommunity


class Post(WithUpdates, WithRichTextContent, PublishAble, WithArchivableAuthor, LikeAble, CommentAble, SaveAble,
           ShareAble, WithAbsoluteUrl, WithImage, WithOptionalCommunity, models.Model):

    title = models.CharField(_('Title'), max_length=160, db_index=True)
    meta = models.CharField(_('Meta'), max_length=72, null=True)

    active = PublishedManager()
    report_builder_model_manager = active
    all_objects = models.Manager()

    needs_approval = False
    dis_approval_reasons = ''

    language = models.ForeignKey('language.Language', default=settings.LANGUAGE_CODE, to_field='name')

    def __unicode__(self):
        return 'Community: %s - %s' % (unicode(self.community), unicode(self.title[:20]))

    class Meta:
        ordering = ('publish_date', )
        verbose_name = _('Post')
        verbose_name_plural = _("Posts")

source/apps/post/views.py
from django.http import Http404
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django import forms
from django.forms import widgets
from django.forms.utils import flatatt
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from lib.behaviours.views import WithAuthor
from lib.data_views.exceptions import RecordDoesNotExist

from apps.comment.queries import AddPostComments
from apps.core.views import ModelFormView
from apps.core.views import AjaxFormResponseMixin
from apps.menu.views import WithUserMenu
from apps.post.queries import PostShareCount
from apps.wall.queries import WallPostDataView

from .models import Post
from .forms import PostForm


class PostDetail(WithUserMenu, DetailView):
    template_name = 'post/post_detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['is_expanded'] = True

        AddPostComments.all(post=self.object)

        return context


class PostCreate(WithAuthor, ModelFormView, AjaxFormResponseMixin, CreateView):
    template_name = 'post/popup/_new.html'
    form_class = PostForm

    http_method_names = ['get', 'post']

    def get_context_data(self):
        if hasattr(self, 'object'):
            if self.object.needs_approval:
                return {'approval': _('This post is sent for approval because: {0}').format(unicode(self.object.dis_approval_reasons))}
        return {}


"""
    GET op AjaxModelFormDeleteView geeft ajax response met {"form": <html form>}
        is een ModelForm

    POST op AjaxModelFormDeleteView validate form met ge-submitte data
        als data invalid:
            http 400, {"form": <html form met errors>}
        anders
            http 200, {"success": true, "data": {"message": "<text|object>"}

"""


class ButtonChoicesWidget(widgets.Input):
    input_type = 'submit'

    def __init__(self, attrs=None, choices=()):
        if attrs is not None:
            self.input_type = attrs.pop('type', self.input_type)
        super(ButtonChoicesWidget, self).__init__(attrs)
        self.choices = choices

    def render(self, name, value, attrs=None):
        out = format_html('<span{}>', flatatt(self.build_attrs(attrs)))
        for choice in self.choices:
            out += super(ButtonChoicesWidget, self).render(choice[0], choice[1],
                                                           self.build_attrs(attrs, type=self.input_type, name=name))
        return mark_safe(out + '</span>')


class ButtonChoicesField(forms.ChoiceField):
    widget = ButtonChoicesWidget


class AjaxModelFormDeleteView(AjaxFormResponseMixin, UpdateView):
    def __init__(self, *args, **kwargs):
        self.model = self.form_class._meta.model
        super(AjaxModelFormDeleteView, self).__init__(*args, **kwargs)


class PostDeleteForm(forms.ModelForm):
    YES = 'Yes, delete post'
    NO = 'No'

    CHOICES = (
        (YES, YES),
        (NO, NO)
    )

    yes_no = ButtonChoicesField(choices=CHOICES, label=_('Are you sure you want to delete this post?'), required=True)

    def save(self, commit=True):
        if self.cleaned_data['yes_no'] == self.YES:
            # if this post in on this user's wall and the user is not the owner of this post
            # remove the post from this user's wall
            try:
                wall_post = WallPostDataView.get(user_id=self.data.get('author', 0), post_id=self.instance.pk)
                wall_post.delete()

                PostShareCount.update(self.instance)
            except RecordDoesNotExist:
                raise Http404

            # if the post is owned by this user, delete the post (and let it cascade)
            if self.data.get('author', 0) == self.instance.author.pk:
                self.instance.delete()

        return self.instance

    class Meta:
        model = Post
        fields = (
            'id',
        )


class PostDelete(WithAuthor, AjaxModelFormDeleteView):
    template_name = 'post/popup/_delete.html'
    form_class = PostDeleteForm

    def __init__(self, *args, **kwargs):
        self.is_deleted = False
        super(PostDelete, self).__init__(*args, **kwargs)

    def form_valid(self, form):
        self.is_deleted = bool(str(form.data['yes_no']) == str(form.YES))
        return super(PostDelete, self).form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs = super(PostDelete, self).get_context_data(**kwargs)
        kwargs['valid'] = self.is_deleted
        return kwargs

source/apps/post/templates/post/_featured_items.html
{% load thumbnail i18n %}
<div class="featured-items">
    <div class="featured-item community">
        <h3 class="title">{% trans "Hottest Community" %}</h3>
        {% if suggestions.hottest_community %}
        <a href="{% url 'wall:community' pk=suggestions.hottest_community.pk %}">
            <span class="communitystamp">
                {{ suggestions.hottest_community.name }}
                <i class="community-icon"><img src="{{ suggestions.hottest_community.icon|thumbnail_url:'community_icon_double' }}" width="16" height="16"></i>
            </span>
        </a>
        {% else %}
            {% trans "There is no Hottest Community at the moment" %}
        {% endif %}
    </div>

    <div class="featured-item">
        <h3 class="title">{% trans "Hottest Post" %} <i class="fa fa-fire"></i></h3>
        {% if suggestions.hottest_post %}
            <a href="{{ suggestions.hottest_post.get_absolute_url }}">{{ suggestions.hottest_post.title }}</a>
        {% else %}
            {% trans "There is no hottest post at the moment" %}
        {% endif %}
    </div>

    <div class="featured-item">
        <h3 class="title">{% trans "Promoted Post" %} <i class="fa fa-bookmark"></i></h3>
        {% if suggestions.promoted_post %}
            <a href="{{ suggestions.promoted_post.get_absolute_url }}">{{ suggestions.promoted_post.title }}</a>
        {% else %}
            {% trans "There is no promoted post at the moment" %}
        {% endif %}
    </div>
</div>

source/apps/post/templates/post/_post.html
{% load rules i18n %}{% rules user=request.user community=community comment=comment post=post wall=wall as rules %}
<div
    class="post {% if is_expanded %} is-expanded{% endif %}"
    id="post{{ post.id }}"
    {% if own_wall %}
        {% if post.is_read %}
            data-is-read="{{ post.id }}"
        {% else %}
            data-is-not-read="{{ post.id }}"
        {% endif %}
    {% endif %}
    data-comments-load="{% url 'comment:first_and_last' pk=post.pk %}"
>
    <div class="post-header">
        {% include "post/_post_header.html" %}
    </div>
    <div class="post-content">
        {% include "post/_post_content.html" %}
    </div>
    <div class="post-footer">
        {% include "post/_post_footer.html" %}
    </div>
    <div class="post-comments">
        <div class="comments">
            {% if show_all_comments %}
                {% for comment in post.comments %}
                    {% include 'comment/_comment.html' %}
                {% endfor %}
            {% endif %}
        </div>
        {% if rules.is_allowed_on_wall %}
            <div class="comment-form">
                {% include "comment/_create.html" %}
            </div>
        {% endif %}
    </div>
</div> <!-- END post -->

source/apps/post/templates/post/_post_comments.html
{% load rules i18n %}{% rules user=request.user community=community comment=comment post=post wall=wall as rules %}
{% include 'comment/list.html' with comments=post.first_comments %}

<span class="btn btn-more-comments" data-comments-more="{% url 'comment:more' pk=post.pk %}">{% trans "Load more comments (NUMBER HERE)" %}</span>

{% include 'comment/list.html' with comments=post.comments %}

{% if rules.is_allowed_on_wall %}
<div class="comment-form">
    {% include "comment/_create.html" %}
</div>
{% endif %}

source/apps/post/templates/post/_post_content.html
{% load thumbnail %}
<div class="post-details">
    <span class="post-timestamp">
        <i class="fa fa-clock-o"></i> {{ post.created_jalali }}
    </span>
    {% if post.community %}
    <span class="communitystamp">
        <bdi><a class="community-link" href="{% url 'wall:community' pk=post.community.pk %}">{{ post.community.name }}</a></bdi>
        <i class="community-icon"><img src="{{ post.community.icon|thumbnail_url:'community_icon_double' }}" width="16" height="16"></i>
    </span>
    {% endif %}
</div>

<bdi><p>{{ post.message|safe }}</p></bdi>

{% if post.image %}
    <a class="post-image" href="{{ post.image|thumbnail_url:'post_big' }}" target="_blank">
        <img src="{{ post.image|thumbnail_url:'post_normal' }}" alt="{{ post.title }}">
    </a>

{% endif %}

source/apps/post/templates/post/_post_footer.html
{% load rules i18n %}{% rules user=request.user community=community comment=comment post=post wall=wall as rules %}
<div class="post-footer">
    {% if rules.can_share %}
    <span data-share-post="{{ post.id }}" class="{% if rules.has_shared_post %}is-active{% endif %}">
        <a href="#" class="inactive footer-button share-post-button share fleft">
            <i class="fa fa-share"></i> {% trans "Share" %} (<span class="count">{{ post.share_count }}</span>)
        </a>
        <span class="active footer-button fleft">
            <i class="fa fa-check is-shared"></i> {% trans "Shared" %} (<span class="count">{{ post.share_count }}</span>)
        </span>
    </span>
    {% endif %}
    {% if rules.can_like %}
        <a data-like-post="{{ post.id }}" href="#" class="footer-button like-post-button fleft{% if rules.has_liked_post %} is-active{% endif %}">
            <span class="active">
                <i class="fa fa-heart is-liked"></i> {% trans "Unlike" %} (<span class="count">{{ post.like_count }}</span>)
            </span>
            <span class="inactive">
               <i class="fa fa-heart"></i> {% trans "Like" %} (<span class="count">{{ post.like_count }}</span>)
            </span>
        </a>
    {% else %}
            <span class="inactive">
               <i class="fa fa-heart"></i> {% trans "Like" %} (<span class="count">{{ post.like_count }}</span>)
            </span>
    {% endif %}
    <a href="#" data-comments-toggle="{{ post.id }}" class="footer-button comment-post-button comment fleft">
        <i class="fa fa-comments"></i> {% trans "Comments" %} (<span class="count">{{ post.comment_count }}</span>)
    </a>

    {% ifequal post.author.username 'deleted' %}
        <span class="fright">{{ post.author.username }}</span>
    {% else %}
        <a class="author-link fright" href="{% url 'wall:detail' post.author.id %}">{{ post.author.username }}</a>
    {% endifequal %}
    {% if rules.can_follow %}
        <span data-follow-user="{{ post.author.id }}" class="account-button footer-button follow fright{% if rules.following_author %} is-active{% endif %}">
            <span class="active" style="display: none;"><i class="fa fa-user-times"></i> {% trans "Unfollow" %}&nbsp;</span>
            <span class="inactive"><i class="fa fa-user-plus"></i> {% trans "Follow" %}&nbsp;</span>
        </span>
    {% endif %}

    {% if post.share_source %}
        <span class="share_source footer-button fright">
            <i class="fa fa-share"></i> {% trans "Shared on" %} <a class="author-link" href="{% url 'wall:detail' post.share_source.id %}">{{ post.share_source.username }}</a>
        </span>
    {% endif %}

</div>

source/apps/post/templates/post/_post_header.html
{% load i18n rules %}{% rules user=request.user community=community comment=comment post=post wall=wall as rules %}
{% if rules.can_save %}

<a title="{% trans "Add to favorites"%}" data-star-post="{{ post.id }}" class="star-post-button post-button{% if rules.has_saved_post %} is-active{% endif %}">
    <span class="active">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-star fa-stack-1x fa-inverse is-starred"></i>
        </span>
    </span>
    <span class="inactive">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-star fa-stack-1x fa-inverse"></i>
        </span>
    </span>
</a>
{% endif %}
{% if rules.can_remove %}
    <a title='{% trans "Remove this post" %}' data-remove-post="{{ post.id }}" class="remove-post-button post-button">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-trash fa-stack-1x fa-inverse"></i>
        </span>
    </a>
{% endif %}
{% if rules.can_report %}
    <a title="{% trans "Report this post" %}" data-report-post="{{ post.id }}" class="report-post-button post-button">
        <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-exclamation-triangle fa-stack-1x fa-inverse"></i>
        </span>
    </a>
{% endif %}
<a href="{% url 'post:detail' pk=post.pk %}"><h2 class="post-title"><bdi>{{ post.title }}</bdi></h2></a>

source/apps/post/templates/post/post_detail.html
{% extends "core/base.html" %}
{% load i18n %}

{% block page_title %}{{ post.title }}{% endblock page_title %}

{% block content %}
    {% if request.user.is_anonymous and not post.community %}
        <h1>{% trans "You need to login to see this page" %}</h1>
    {% else %}
        {% include 'post/_post.html' with show_all_comments=True %}
    {% endif %}
{% endblock content %}